version: "3"

services:
  node_0:
    container_name: swn_cluster_node_0
    build: .
    networks:
      cluster:
        ipv4_address: 172.16.0.100
    volumes:
      - ./disk_0:/dev/disk
    privileged: true
    tty: true
  node_1:
    container_name: swn_cluster_node_1
    build: .
    networks:
      cluster:
        ipv4_address: 172.16.0.101
    volumes:
      - ./disk_1:/dev/disk
    privileged: true
    tty: true
  node_2:
    container_name: swn_cluster_node_2
    build: .
    networks:
      cluster:
        ipv4_address: 172.16.0.102
    volumes:
      - ./disk_2:/dev/disk
    privileged: true
    tty: true

networks:
  cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
